# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: qpc.spec

upstream_project_url: https://github.com/quipucords/qpc

jobs:
  - job: copr_build
    trigger: pull_request
    targets: &targets_list
      # we officially support RHEL 8 and RHEL 9 downstream.
      - rhel-8-x86_64
      - rhel-8-aarch64
      - rhel-9-x86_64
      - rhel-9-aarch64
      # we also build for RHEL 10
      - rhel-10-x86_64
      - rhel-10-aarch64
      # fedora is like an even farther future preview.
      - fedora-42-x86_64
      - fedora-42-aarch64

  - job: copr_build
    trigger: commit
    branch: "^main$"
    owner: "@quipucords"
    project: "qpc-latest"
    preserve_project: True
    targets: *targets_list

  - job: copr_build
    trigger: release
    owner: "@quipucords"
    project: "qpc"
    preserve_project: True
    targets: *targets_list
