#!/bin/bash
mkdir -p ~/.config/qpc ~/.local/share/qpc
podman run -it --rm \
    -v ~/.config/qpc:/root/.config/qpc \
    -v ~/.local/share/qpc:/root/.local/share/qpc \
    --entrypoint='/app/qpc/deploy/docker_run.sh' \
    qpc "$@"
