"""File to hold release constants."""
VERSION = "1.0.1"
AUTHOR = "QPC Team"
AUTHOR_EMAIL = "qpc@redhat.com"
PKG_NAME = "qpc"
ENTRYPOINT = f"{PKG_NAME}=qpc.__main__:main"
URL = "https://github.com/quipucords/qpc"
