"""Constants for the Report commands."""

SUBCOMMAND = "report"

DETAILS = "details"
DEPLOYMENTS = "deployments"
INSIGHTS = "insights"
AGGREGATE = "aggregate"
MERGE = "merge"
UPLOAD = "upload"
MERGE_STATUS = "merge-status"
DOWNLOAD = "download"
REPORT_URI = "/api/v1/reports/"
DETAILS_PATH_SUFFIX = "/details/"
DEPLOYMENTS_PATH_SUFFIX = "/deployments/"
AGGREGATE_PATH_SUFFIX = "/aggregate/"
INSIGHTS_PATH_SUFFIX = "/insights/"
ASYNC_MERGE_URI = "/api/v1/reports/merge/"
ASYNC_UPLOAD_URI = "/api/v1/reports/"
