name: Test QPC

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          [
            lint,
            test-coverage,
        ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetches all commits/tags

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
          cache: "poetry"
          cache-dependency-path: "poetry.lock"

      - name: Install dependencies
        run: poetry install

      - name: Test phase
        run: make ${{ matrix.type }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
  