name: Test QPC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"] # Expand like ["3.12", "3.13"] to test more versions.
        type:
          [
            config-verify,
            manpage-test,
            lint,
            test-coverage,
        ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetches all commits/tags

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: "pyproject.toml"

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: uv sync

      - name: Test phase
        run: make ${{ matrix.type }}

      - name: Report coverage
        if: ${{ success() && contains(matrix.type, 'test-coverage') }}
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }} # required
          # verbose: true # optional (default = false)
