name: Test QPC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"] # Expand like ["3.12", "3.13"] to test more versions.
        type:
          [
            config-verify,
            manpage-test,
            lint,
            test-coverage,
        ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetches all commits/tags

      - name: Install poetry
        run: pipx install "poetry<2"

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: "poetry.lock"

      - name: Install dependencies
        run: poetry install --with build

      - name: Test phase
        run: make ${{ matrix.type }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
