name: Test QPC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-dependencies:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
          cache: "poetry"
          cache-dependency-path: "poetry.lock"

      - name: Check dependencies
        run: |
          make lock-main-requirements
          make check-requirements
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          [
            manpage-test,
            lint,
            test-coverage,
        ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetches all commits/tags

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
          cache: "poetry"
          cache-dependency-path: "poetry.lock"

      - name: Install dependencies
        run: poetry install --with build

      - name: Test phase
        run: make ${{ matrix.type }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
